FROM ubuntu:19.10
MAINTAINER cetc15

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

COPY sources.list /etc/apt/sources.list
RUN apt update &&                  \
    apt upgrade -y &&              \
    apt dist-upgrade -y &&         \
    apt install -y  --no-install-recommends \
        qt5-default  fcitx-frontend-qt5 && \            
    apt clean

WORKDIR /home/root/
